/**
 * SENT — ABI export.
 *
 * §1064 permits exactly one canonical source for contract ABIs and events. That
 * source is the compiler output, and this copies it into `packages/contracts` so
 * the SDK, indexer, API and frontend all bind to the same artifacts.
 *
 * Hand-edited ABIs are the failure mode this prevents: a hand-copied signature
 * drifts from the deployed contract, and the resulting calldata is silently wrong
 * rather than failing to compile.
 *
 * Run: pnpm abis
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";

const ARTIFACT_DIR = "contracts/out";
const OUT_DIR = "packages/contracts/src";

/** Contracts whose ABI is part of the public surface. */
const EXPORTED = [
  "LaunchpadFactory",
  "LaunchMarket",
  "LaunchToken",
  "FeeVault",
  "ReferencePriceAdapter",
  "GraduationRouter",
  "PermanentLiquidityLock",
  "HolderRewardVault",
  "XStockRegistry",
  "WrappedXStock",
  "WrappedXStockFactory",
] as const;

interface Artifact {
  abi: unknown[];
  bytecode?: { object?: string };
}

function loadArtifact(name: string): Artifact {
  const path = `${ARTIFACT_DIR}/${name}.sol/${name}.json`;
  if (!existsSync(path)) {
    throw new Error(
      `missing artifact for ${name} at ${path} — run \`forge build --root contracts\` first`,
    );
  }
  return JSON.parse(readFileSync(path, "utf8")) as Artifact;
}

mkdirSync(OUT_DIR, { recursive: true });

const exports: string[] = [];

for (const name of EXPORTED) {
  const artifact = loadArtifact(name);
  const constName = `${name.replace(/^[A-Z]/, (c) => c.toLowerCase())}Abi`;

  const body =
    `// GENERATED by packages/contracts/scripts/export-abis.ts — DO NOT EDIT.\n` +
    `// Source of truth is the Solidity compiler output (§1064). A hand-edited ABI\n` +
    `// drifts from the deployed contract and produces silently wrong calldata.\n\n` +
    `export const ${constName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;

  writeFileSync(`${OUT_DIR}/${name}.abi.ts`, body);
  exports.push(`export { ${constName} } from "./${name}.abi.ts";`);
}

writeFileSync(
  `${OUT_DIR}/index.ts`,
  `// GENERATED by packages/contracts/scripts/export-abis.ts — DO NOT EDIT.\n\n` +
    exports.join("\n") +
    "\n",
);

console.log(`\nABIs exported to ${OUT_DIR}`);
for (const name of EXPORTED) console.log(`  ${name}`);
console.log("");
