// GENERATED by packages/contracts/scripts/export-abis.ts — DO NOT EDIT.
// Source of truth is the Solidity compiler output (§1064). A hand-edited ABI
// drifts from the deployed contract and produces silently wrong calldata.

export const wrappedXStockFactoryAbi = [
  {
    "type": "function",
    "name": "create",
    "inputs": [
      {
        "name": "underlying",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "wrapper",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "predict",
    "inputs": [
      {
        "name": "underlying",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "wrapperAt",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "wrapperCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "wrapperOf",
    "inputs": [
      {
        "name": "underlying",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "wrapper",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "WrapperCreated",
    "inputs": [
      {
        "name": "underlying",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "wrapper",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "symbol",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyCreated",
    "inputs": [
      {
        "name": "underlying",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "wrapper",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
