// GENERATED by packages/contracts/scripts/export-abis.ts — DO NOT EDIT.
// Source of truth is the Solidity compiler output (§1064). A hand-edited ABI
// drifts from the deployed contract and produces silently wrong calldata.

export const xStockRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "disableAsset",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reason",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "enableAsset",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAsset",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct XStockRegistry.Asset",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "decimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "coreTokenIndex",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "evmExtraWeiDecimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "gates",
            "type": "tuple",
            "internalType": "struct XStockRegistry.Gates",
            "components": [
              {
                "name": "canonicalRepresentation",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "transferBehaviour",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "multiplierBehaviour",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "priceSource",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "haltSource",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "hyperSwapCompatible",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "normalizedAccountingTested",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "legalReviewed",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          },
          {
            "name": "enabledForNewLaunches",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "verifiedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "exists",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "governance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isLaunchable",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "launchableAssets",
    "inputs": [],
    "outputs": [
      {
        "name": "result",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registerAsset",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "decimals_",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "coreTokenIndex",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "evmExtraWeiDecimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registeredAt",
    "inputs": [
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registeredCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setGates",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "gates",
        "type": "tuple",
        "internalType": "struct XStockRegistry.Gates",
        "components": [
          {
            "name": "canonicalRepresentation",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "transferBehaviour",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "multiplierBehaviour",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "priceSource",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "haltSource",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "hyperSwapCompatible",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "normalizedAccountingTested",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "legalReviewed",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferGovernance",
    "inputs": [
      {
        "name": "newGovernance",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AssetDisabled",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "reason",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssetEnabled",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "verifiedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AssetRegistered",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "coreTokenIndex",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "decimals",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GatesUpdated",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "gates",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct XStockRegistry.Gates",
        "components": [
          {
            "name": "canonicalRepresentation",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "transferBehaviour",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "multiplierBehaviour",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "priceSource",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "haltSource",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "hyperSwapCompatible",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "normalizedAccountingTested",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "legalReviewed",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      },
      {
        "name": "allPassed",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GovernanceTransferred",
    "inputs": [
      {
        "name": "from",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadyRegistered",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AssetRebases",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "currentMultiplier",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "GatesNotAllPassed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnknownAsset",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
