// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {Curve} from "../src/lib/Curve.sol";
import {Fees} from "../src/lib/Fees.sol";

/// @notice Proves the Solidity and TypeScript implementations of the canonical
///         curve and fee math agree exactly (Masterplan §1064).
///
/// WHY THIS TEST EXISTS
/// --------------------
/// §1064 permits exactly one canonical source for curve math, fee math and
/// Stockback accounting. SENT necessarily has two implementations of that one
/// source: Solidity on-chain, TypeScript in `packages/economics` for the SDK,
/// quoting, the indexer and simulation.
///
/// Two implementations of one truth is precisely how they drift. The headers of
/// `Curve.sol` and `Fees.sol` claim they are differential-tested; this file is
/// what makes that claim true rather than aspirational.
///
/// WHY AGREEMENT IS EVIDENCE, NOT TAUTOLOGY
/// ----------------------------------------
/// The two implementations reach their answers by different routes. TypeScript
/// uses arbitrary-precision BigInt on the full discriminant. Solidity CANNOT —
/// `B²` overflows uint256 for any xStock below roughly $93 — so it rescales by
/// `dP` before squaring and corrects against the forward function.
///
/// Different arithmetic, same specification:
///
///     tokensOutFor(q, netIn) = max { Δ : quoteInFor(q, Δ) <= netIn }
///
/// The fixtures deliberately span that overflow regime, so agreement across all
/// of them is a real cross-check of two independent derivations.
///
/// Fixtures are generated by `pnpm fixtures` and committed. If either
/// implementation changes, this test fails until the fixtures are regenerated
/// AND the other implementation is brought back in line.
contract DifferentialTest is Test {
    string json;

    function setUp() public {
        json = vm.readFile("test/fixtures/economics.json");
    }

    function _u(string memory key) internal view returns (uint256[] memory) {
        return vm.parseJsonUintArray(json, key);
    }

    // -----------------------------------------------------------------------
    // Curve
    // -----------------------------------------------------------------------

    function test_curveMatchesTypeScriptExactly() public view {
        uint256[] memory p0 = _u(".curve.p0");
        uint256[] memory q = _u(".curve.q");
        uint256[] memory netIn = _u(".curve.netIn");
        uint256[] memory expectTokensOut = _u(".curve.expectTokensOut");
        uint256[] memory expectQuoteIn = _u(".curve.expectQuoteIn");
        uint256[] memory expectGrossOut = _u(".curve.expectGrossOut");
        uint256[] memory expectCollateral = _u(".curve.expectCollateral");
        uint256[] memory expectPrice = _u(".curve.expectPrice");

        assertGt(p0.length, 400, "fixture set must be substantial");

        for (uint256 i = 0; i < p0.length; i++) {
            Curve.Params memory p = Curve.params(p0[i]);

            assertEq(
                Curve.tokensOutFor(p, q[i], netIn[i]),
                expectTokensOut[i],
                string.concat("tokensOutFor mismatch at case ", vm.toString(i))
            );

            assertEq(
                Curve.quoteInFor(p, q[i], expectTokensOut[i]),
                expectQuoteIn[i],
                string.concat("quoteInFor mismatch at case ", vm.toString(i))
            );

            assertEq(
                Curve.grossOutFor(p, q[i] + expectTokensOut[i], expectTokensOut[i]),
                expectGrossOut[i],
                string.concat("grossOutFor mismatch at case ", vm.toString(i))
            );

            assertEq(
                Curve.collateralAt(p, q[i]),
                expectCollateral[i],
                string.concat("collateralAt mismatch at case ", vm.toString(i))
            );

            assertEq(
                Curve.marginalPrice(p, q[i]),
                expectPrice[i],
                string.concat("marginalPrice mismatch at case ", vm.toString(i))
            );
        }
    }

    // -----------------------------------------------------------------------
    // Fees
    // -----------------------------------------------------------------------

    function test_feesMatchTypeScriptExactly() public view {
        uint256[] memory notional = _u(".fees.notional");
        uint256[] memory buyCore = _u(".fees.buyCore");
        uint256[] memory buyCreator = _u(".fees.buyCreator");
        uint256[] memory buyPlatform = _u(".fees.buyPlatform");
        uint256[] memory buyStockback = _u(".fees.buyStockback");
        uint256[] memory buyNet = _u(".fees.buyNet");
        uint256[] memory sellCore = _u(".fees.sellCore");
        uint256[] memory sellCreator = _u(".fees.sellCreator");
        uint256[] memory sellPlatform = _u(".fees.sellPlatform");
        uint256[] memory sellStockback = _u(".fees.sellStockback");
        uint256[] memory sellNet = _u(".fees.sellNet");

        for (uint256 i = 0; i < notional.length; i++) {
            Fees.Breakdown memory b = Fees.forBuy(notional[i]);
            string memory at = string.concat(" at case ", vm.toString(i));

            assertEq(b.coreFee, buyCore[i], string.concat("buy core", at));
            assertEq(b.creatorFee, buyCreator[i], string.concat("buy creator", at));
            assertEq(b.platformFee, buyPlatform[i], string.concat("buy platform", at));
            assertEq(b.stockback, buyStockback[i], string.concat("buy stockback", at));
            assertEq(b.net, buyNet[i], string.concat("buy net", at));

            Fees.Breakdown memory s = Fees.forSell(notional[i]);
            assertEq(s.coreFee, sellCore[i], string.concat("sell core", at));
            assertEq(s.creatorFee, sellCreator[i], string.concat("sell creator", at));
            assertEq(s.platformFee, sellPlatform[i], string.concat("sell platform", at));
            assertEq(s.stockback, sellStockback[i], string.concat("sell stockback", at));
            assertEq(s.net, sellNet[i], string.concat("sell net", at));
        }
    }

    // -----------------------------------------------------------------------
    // Post-graduation split
    // -----------------------------------------------------------------------

    function test_postGradSplitMatchesTypeScriptExactly() public view {
        uint256[] memory revenue = _u(".postGrad.revenue");
        uint256[] memory creatorX = _u(".postGrad.creatorXStock");
        uint256[] memory stockbackX = _u(".postGrad.stockbackXStock");
        uint256[] memory platformX = _u(".postGrad.platformXStock");
        uint256[] memory creatorT = _u(".postGrad.creatorToken");
        uint256[] memory stockbackT = _u(".postGrad.stockbackToken");
        uint256[] memory platformT = _u(".postGrad.platformToken");

        for (uint256 i = 0; i < revenue.length; i++) {
            string memory at = string.concat(" at case ", vm.toString(i));

            (uint256 c1, uint256 s1, uint256 p1) = Fees.splitPostGrad(revenue[i], true);
            assertEq(c1, creatorX[i], string.concat("post-grad creator (xStock)", at));
            assertEq(s1, stockbackX[i], string.concat("post-grad stockback (xStock)", at));
            assertEq(p1, platformX[i], string.concat("post-grad platform (xStock)", at));

            (uint256 c2, uint256 s2, uint256 p2) = Fees.splitPostGrad(revenue[i], false);
            assertEq(c2, creatorT[i], string.concat("post-grad creator (TOKEN)", at));
            assertEq(s2, stockbackT[i], string.concat("post-grad stockback (TOKEN)", at));
            assertEq(p2, platformT[i], string.concat("post-grad platform (TOKEN)", at));
        }
    }
}
