// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {Curve} from "../src/lib/Curve.sol";
import {Fees} from "../src/lib/Fees.sol";

/// @notice Proves the Solidity and TypeScript implementations of the canonical
///         curve and fee math agree exactly (Masterplan §1064).
///
/// WHY THIS TEST EXISTS
/// --------------------
/// §1064 permits exactly one canonical source for curve math, fee math and
/// Stockback accounting. SENT necessarily has two implementations of that one
/// source: Solidity on-chain, TypeScript in `packages/economics` for the SDK,
/// quoting, the indexer and simulation.
///
/// Two implementations of one truth is precisely how they drift. The headers of
/// `Curve.sol` and `Fees.sol` claim they are differential-tested; this file is
/// what makes that claim true rather than aspirational.
///
/// WHY AGREEMENT IS EVIDENCE, NOT TAUTOLOGY
/// ----------------------------------------
/// The two implementations reach their answers by different routes. TypeScript
/// uses arbitrary-precision BigInt on the full discriminant. Solidity CANNOT —
/// `B²` overflows uint256 for any xStock below roughly $93 — so it rescales by
/// `dP` before squaring and corrects against the forward function.
///
/// Different arithmetic, same specification:
///
///     tokensOutFor(q, netIn) = max { Δ : quoteInFor(q, Δ) <= netIn }
///
/// The fixtures deliberately span that overflow regime, so agreement across all
/// of them is a real cross-check of two independent derivations.
///
/// Fixtures are generated by `pnpm fixtures` and committed. If either
/// implementation changes, this test fails until the fixtures are regenerated
/// AND the other implementation is brought back in line.
contract DifferentialTest is Test {
    string json;

    function setUp() public {
        json = vm.readFile("test/fixtures/economics.json");
    }

    function _u(string memory key) internal view returns (uint256[] memory) {
        return vm.parseJsonUintArray(json, key);
    }

    // -----------------------------------------------------------------------
    // Curve
    // -----------------------------------------------------------------------

    function test_curveMatchesTypeScriptExactly() public view {
        uint256[] memory p0 = _u(".curve.p0");
        uint256[] memory q = _u(".curve.q");
        uint256[] memory netIn = _u(".curve.netIn");
        uint256[] memory expectTokensOut = _u(".curve.expectTokensOut");
        uint256[] memory expectQuoteIn = _u(".curve.expectQuoteIn");
        uint256[] memory expectGrossOut = _u(".curve.expectGrossOut");
        uint256[] memory expectCollateral = _u(".curve.expectCollateral");
        uint256[] memory expectPrice = _u(".curve.expectPrice");

        assertGt(p0.length, 400, "fixture set must be substantial");

        for (uint256 i = 0; i < p0.length; i++) {
            Curve.Params memory p = Curve.params(p0[i]);

            assertEq(
                Curve.tokensOutFor(p, q[i], netIn[i]),
                expectTokensOut[i],
                string.concat("tokensOutFor mismatch at case ", vm.toString(i))
            );

            assertEq(
                Curve.quoteInFor(p, q[i], expectTokensOut[i]),
                expectQuoteIn[i],
                string.concat("quoteInFor mismatch at case ", vm.toString(i))
            );

            assertEq(
                Curve.grossOutFor(p, q[i] + expectTokensOut[i], expectTokensOut[i]),
                expectGrossOut[i],
                string.concat("grossOutFor mismatch at case ", vm.toString(i))
            );

            assertEq(
                Curve.collateralAt(p, q[i]),
                expectCollateral[i],
                string.concat("collateralAt mismatch at case ", vm.toString(i))
            );

            assertEq(
                Curve.marginalPrice(p, q[i]),
                expectPrice[i],
                string.concat("marginalPrice mismatch at case ", vm.toString(i))
            );
        }
    }

    // -----------------------------------------------------------------------
    // Fees
    // -----------------------------------------------------------------------

    /// @dev Buy and sell are separate functions purely to keep the number of live
    ///      locals under the stack limit; eleven arrays in one frame does not fit
    ///      even through the IR pipeline.
    function test_buyFeesMatchTypeScriptExactly() public view {
        uint256[] memory notional = _u(".fees.notional");
        uint256[] memory core = _u(".fees.buyCore");
        uint256[] memory creator = _u(".fees.buyCreator");
        uint256[] memory platform = _u(".fees.buyPlatform");
        uint256[] memory stockback = _u(".fees.buyStockback");
        uint256[] memory net = _u(".fees.buyNet");

        for (uint256 i = 0; i < notional.length; i++) {
            Fees.Breakdown memory b = Fees.forBuy(notional[i]);
            string memory at = string.concat(" at buy case ", vm.toString(i));

            assertEq(b.coreFee, core[i], string.concat("core", at));
            assertEq(b.creatorFee, creator[i], string.concat("creator", at));
            assertEq(b.platformFee, platform[i], string.concat("platform", at));
            assertEq(b.stockback, stockback[i], string.concat("stockback", at));
            assertEq(b.net, net[i], string.concat("net", at));
        }
    }

    function test_sellFeesMatchTypeScriptExactly() public view {
        uint256[] memory notional = _u(".fees.notional");
        uint256[] memory core = _u(".fees.sellCore");
        uint256[] memory creator = _u(".fees.sellCreator");
        uint256[] memory platform = _u(".fees.sellPlatform");
        uint256[] memory stockback = _u(".fees.sellStockback");
        uint256[] memory net = _u(".fees.sellNet");

        for (uint256 i = 0; i < notional.length; i++) {
            Fees.Breakdown memory s = Fees.forSell(notional[i]);
            string memory at = string.concat(" at sell case ", vm.toString(i));

            assertEq(s.coreFee, core[i], string.concat("core", at));
            assertEq(s.creatorFee, creator[i], string.concat("creator", at));
            assertEq(s.platformFee, platform[i], string.concat("platform", at));
            assertEq(s.stockback, stockback[i], string.concat("stockback", at));
            assertEq(s.net, net[i], string.concat("net", at));
        }
    }

    // -----------------------------------------------------------------------
    // Post-graduation split
    // -----------------------------------------------------------------------

    function test_postGradXStockSplitMatchesTypeScript() public view {
        uint256[] memory revenue = _u(".postGrad.revenue");
        uint256[] memory creator = _u(".postGrad.creatorXStock");
        uint256[] memory stockback = _u(".postGrad.stockbackXStock");
        uint256[] memory platform = _u(".postGrad.platformXStock");

        for (uint256 i = 0; i < revenue.length; i++) {
            (uint256 c, uint256 s, uint256 p) = Fees.splitPostGrad(revenue[i], true);
            string memory at = string.concat(" at case ", vm.toString(i));
            assertEq(c, creator[i], string.concat("creator (xStock)", at));
            assertEq(s, stockback[i], string.concat("stockback (xStock)", at));
            assertEq(p, platform[i], string.concat("platform (xStock)", at));
        }
    }

    function test_postGradTokenSplitMatchesTypeScript() public view {
        uint256[] memory revenue = _u(".postGrad.revenue");
        uint256[] memory creator = _u(".postGrad.creatorToken");
        uint256[] memory stockback = _u(".postGrad.stockbackToken");
        uint256[] memory platform = _u(".postGrad.platformToken");

        for (uint256 i = 0; i < revenue.length; i++) {
            (uint256 c, uint256 s, uint256 p) = Fees.splitPostGrad(revenue[i], false);
            string memory at = string.concat(" at case ", vm.toString(i));
            assertEq(c, creator[i], string.concat("creator (TOKEN)", at));
            assertEq(s, stockback[i], string.concat("stockback (TOKEN)", at));
            assertEq(p, platform[i], string.concat("platform (TOKEN)", at));
        }
    }
}
