// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {HolderRewardVault} from "../src/HolderRewardVault.sol";

contract MerkleAsset is ERC20 {
    constructor() ERC20("Mock xStock", "MOCKx") {}

    function mint(address to, uint256 amount) external {
        _mint(to, amount);
    }
}

/// @notice Cross-boundary proof that the off-chain tree builder and the on-chain
///         verifier agree.
///
/// `HolderRewardVault` verifies Merkle proofs; `packages/stockback/src/merkle.ts`
/// builds the trees. Two encodings of one format, and a single byte of
/// disagreement makes every Stockback claim in the system fail — at integration
/// time, long after both halves pass their own tests.
///
/// So nothing here re-implements the tree. The fixtures are produced by the real
/// production builder, and this suite performs REAL claims against the REAL vault
/// using those proofs. A passing run means a holder's proof, generated by the
/// service that will generate it in production, actually pays out on-chain.
///
/// The scenarios target where tree implementations usually break: a single leaf
/// (root == leaf, no pairing), odd counts at one and two levels (a node must be
/// promoted unpaired, not duplicated), unsorted input (attestors computing
/// independently cannot be made to agree on ordering), and zero entitlements
/// (legitimate in a cumulative tree).
contract MerkleTest is Test {
    HolderRewardVault vault;
    MerkleAsset asset;

    address governance = makeAddr("governanceSafe");
    address factory = address(this);
    address market = makeAddr("market");
    address token = makeAddr("launchToken");

    uint256 att1Key = 0xA11CE;
    uint256 att2Key = 0xB0B;
    address att1;
    address att2;

    string json;

    function setUp() public {
        vault = new HolderRewardVault(governance, factory);
        asset = new MerkleAsset();

        att1 = vm.addr(att1Key);
        att2 = vm.addr(att2Key);

        vm.startPrank(governance);
        vault.addAttestor(att1);
        vault.addAttestor(att2);
        vault.setQuorum(2);
        vm.stopPrank();

        vault.registerMarket(market, address(asset));

        json = vm.readFile("test/fixtures/merkle.json");
    }

    function _sign(HolderRewardVault.Commitment memory c) internal view returns (bytes[] memory sigs) {
        bytes32 digest = vault.hashCommitment(c);
        (uint256 loKey, uint256 hiKey) = att1 < att2 ? (att1Key, att2Key) : (att2Key, att1Key);

        sigs = new bytes[](2);
        (uint8 v1, bytes32 r1, bytes32 s1) = vm.sign(loKey, digest);
        (uint8 v2, bytes32 r2, bytes32 s2) = vm.sign(hiKey, digest);
        sigs[0] = abi.encodePacked(r1, s1, v1);
        sigs[1] = abi.encodePacked(r2, s2, v2);
    }

    /// @dev Run one whole fixture scenario end to end: fund, commit the
    ///      TypeScript-built root, activate, then claim for every holder using
    ///      the TypeScript-built proofs.
    function _runScenario(uint256 index, uint256 epochSequence) internal {
        string memory base = string.concat(".scenarios[", vm.toString(index), "]");

        bytes32 root = vm.parseJsonBytes32(json, string.concat(base, ".root"));
        bytes32 datasetHash = vm.parseJsonBytes32(json, string.concat(base, ".datasetHash"));
        uint256 total = vm.parseJsonUint(json, string.concat(base, ".totalCumulative"));
        string memory name = vm.parseJsonString(json, string.concat(base, ".name"));

        // Fund the vault so the conservation check at submission passes (§364).
        asset.mint(address(vault), total);
        vm.prank(market);
        vault.fund(total);

        HolderRewardVault.Commitment memory c = HolderRewardVault.Commitment({
            market: market,
            token: token,
            rewardAsset: address(asset),
            distributionVersion: 1,
            epochSequence: epochSequence,
            totalCumulative: total,
            merkleRoot: root,
            datasetHash: datasetHash
        });

        vault.submitCommitment(c, _sign(c));
        vm.warp(block.timestamp + vault.ACTIVATION_DELAY() + 1);
        vault.activate(market);

        address[] memory accounts = vm.parseJsonAddressArray(json, string.concat(base, ".accounts"));

        uint256 paidOut = 0;

        for (uint256 i = 0; i < accounts.length; i++) {
            string memory at = string.concat(base, ".proofs[", vm.toString(i), "]");
            uint256 cumulative = vm.parseJsonUint(json, string.concat(at, ".cumulative"));
            bytes32[] memory proof = vm.parseJsonBytes32Array(json, string.concat(at, ".proof"));

            uint256 alreadyHeld = asset.balanceOf(accounts[i]);

            if (cumulative == 0) {
                // A zero entitlement is a valid leaf but pays nothing.
                vm.expectRevert(HolderRewardVault.NothingToClaim.selector);
                vault.claim(market, accounts[i], cumulative, proof);
                continue;
            }

            uint256 payout = vault.claim(market, accounts[i], cumulative, proof);

            assertEq(
                payout,
                cumulative,
                string.concat("payout must equal the committed cumulative in: ", name)
            );
            assertEq(
                asset.balanceOf(accounts[i]) - alreadyHeld,
                cumulative,
                string.concat("funds must actually arrive in: ", name)
            );

            paidOut += payout;
        }

        assertEq(paidOut, total, string.concat("every entitlement must be claimable in: ", name));
        assertEq(vault.outstanding(market), 0, string.concat("vault fully settled in: ", name));
    }

    // -----------------------------------------------------------------------

    function test_singleHolder() public {
        _runScenario(0, 1);
    }

    function test_twoHolders() public {
        _runScenario(1, 1);
    }

    /// @dev Odd counts are where a node must be PROMOTED unpaired. Implementations
    ///      that duplicate it instead produce a root the verifier will not match.
    function test_threeHoldersOddPromotion() public {
        _runScenario(2, 1);
    }

    function test_fiveHoldersOddAtTwoLevels() public {
        _runScenario(3, 1);
    }

    function test_sixteenHoldersBalanced() public {
        _runScenario(4, 1);
    }

    /// @dev Independent attestors receive events in whatever order their indexer
    ///      produces. If the root depended on that ordering, no quorum could ever
    ///      form (§404, §406).
    function test_unsortedInputStillVerifies() public {
        _runScenario(5, 1);
    }

    function test_zeroEntitlementIsAValidLeaf() public {
        _runScenario(6, 1);
    }

    // -----------------------------------------------------------------------
    // Negative cases
    // -----------------------------------------------------------------------

    /// @dev A proof from one tree must not verify against another tree's root.
    function test_proofFromAnotherTreeIsRejected() public {
        bytes32 rootA = vm.parseJsonBytes32(json, ".scenarios[4].root");
        uint256 totalA = vm.parseJsonUint(json, ".scenarios[4].totalCumulative");
        bytes32 datasetA = vm.parseJsonBytes32(json, ".scenarios[4].datasetHash");

        asset.mint(address(vault), totalA);
        vm.prank(market);
        vault.fund(totalA);

        HolderRewardVault.Commitment memory c = HolderRewardVault.Commitment({
            market: market,
            token: token,
            rewardAsset: address(asset),
            distributionVersion: 1,
            epochSequence: 1,
            totalCumulative: totalA,
            merkleRoot: rootA,
            datasetHash: datasetA
        });
        vault.submitCommitment(c, _sign(c));
        vm.warp(block.timestamp + vault.ACTIVATION_DELAY() + 1);
        vault.activate(market);

        // A proof and amount taken from a DIFFERENT scenario's tree.
        address account = vm.parseJsonAddress(json, ".scenarios[3].proofs[0].account");
        uint256 cumulative = vm.parseJsonUint(json, ".scenarios[3].proofs[0].cumulative");
        bytes32[] memory foreignProof = vm.parseJsonBytes32Array(json, ".scenarios[3].proofs[0].proof");

        vm.expectRevert(HolderRewardVault.InvalidProof.selector);
        vault.claim(market, account, cumulative, foreignProof);
    }

    /// @dev A valid proof with an inflated amount must fail: the amount is part of
    ///      the leaf, so changing it changes the leaf.
    function test_inflatedAmountWithValidProofIsRejected() public {
        bytes32 root = vm.parseJsonBytes32(json, ".scenarios[4].root");
        uint256 total = vm.parseJsonUint(json, ".scenarios[4].totalCumulative");
        bytes32 datasetHash = vm.parseJsonBytes32(json, ".scenarios[4].datasetHash");

        asset.mint(address(vault), total);
        vm.prank(market);
        vault.fund(total);

        HolderRewardVault.Commitment memory c = HolderRewardVault.Commitment({
            market: market,
            token: token,
            rewardAsset: address(asset),
            distributionVersion: 1,
            epochSequence: 1,
            totalCumulative: total,
            merkleRoot: root,
            datasetHash: datasetHash
        });
        vault.submitCommitment(c, _sign(c));
        vm.warp(block.timestamp + vault.ACTIVATION_DELAY() + 1);
        vault.activate(market);

        address account = vm.parseJsonAddress(json, ".scenarios[4].proofs[0].account");
        uint256 cumulative = vm.parseJsonUint(json, ".scenarios[4].proofs[0].cumulative");
        bytes32[] memory proof = vm.parseJsonBytes32Array(json, ".scenarios[4].proofs[0].proof");

        vm.expectRevert(HolderRewardVault.InvalidProof.selector);
        vault.claim(market, account, cumulative + 1, proof);
    }
}
